#### Exercise 1. Import numpy as np and see the version

In [27]:
import numpy as np

In [28]:
version = np.__version__
print(version)

2.2.6


### Exercise 2. How to create a 1D array?
##### Question : Create a 1D array of numbers from 0 to 9
##### Output : #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
print("1D array:", array)

1D array: [0 1 2 3 4 5 6 7 8 9]


### Exercise 3. How to create a boolean array?
##### Question : Create a 3×3 numpy array of all True’s

In [30]:
bool_array = np.full((3,3), True)
print("3x3 Boolean Array\n", bool_array)

3x3 Boolean Array
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4. How to extract items that satisfy a given condition from 1D array?
1. **Question : Extract all odd numbers from array**
2. **input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])**
3. **output: array([1, 3, 5, 7, 9])**

In [31]:
array = np.arange((10))
conditional_array = np.where((array % 2 == 1))
print("Conditional Array Satisfying given condition:", conditional_array)

Conditional Array Satisfying given condition: (array([1, 3, 5, 7, 9]),)


### Exercise 5. How to replace items that satisfy a condition with another value in numpy array?

1. **Question: Replace all odd numbers in arr with -1**
2. **input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])**
3. **output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])**

In [32]:
array_num =  np.array([0,1,2,3,4,5,6,7,8,9])

#conditional array
array_num[array_num % 2 ==1] = -1
print(array_num)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6. How to replace items that satisfy a condition without affecting the original array?
1. **Replace all odd numbers in arr with -1 without changing arr**
2. **input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])**
3. **output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])**
    **arr** 
    **array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])**

In [37]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
output_array = arr.copy()

output_array[output_array % 2 ==1] = -1

print("Modified Array:", output_array)
print("Original Array:", arr)

Modified Array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Original Array: [0 1 2 3 4 5 6 7 8 9]


## Exercise 7. How to reshape an array?
1. **Question: Convert a 1D array to a 2D array with 2 rows**
2. **input: np.arange(10)**
3. **output: array([[0, 1, 2, 3, 4],**
             **[5, 6, 7, 8, 9]])**


In [62]:
array_1d = np.arange(10)
array_2d = array_1d.reshape(2,-1)
print("Original 1D array",array_1d)
print("Reshaped 2D aray\n", array_2d)

Original 1D array [0 1 2 3 4 5 6 7 8 9]
Reshaped 2D aray
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Exercise 8. How to stack two arrays vertically?

- **input: a = np.arange(10).reshape(2,-1)**
- **b = np.repeat(1, 10).reshape(2,-1)**

- **output: array([[0, 1, 2, 3, 4],**
                **[5, 6, 7, 8, 9],**
                **[1, 1, 1, 1, 1],**
                **[1, 1, 1, 1, 1]])**

In [64]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

vertical_array = np.vstack((a,b))
print("Arrays Stacked Vertically\n", vertical_array)

Arrays Stacked Vertically
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Exercise 9. How to stack two arrays horizontally?
- **input:  a = np.arange(10).reshape(2,-1)**
- **b = np.repeat(1, 10).reshape(2,-1)**

- **output:array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],**
                **[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])**

In [66]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

horizontal_array = np.hstack((a,b))
print("Arrays Stacked Horizontally\n", horizontal_array)

Arrays Stacked Horizontally
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10. How to generate custom sequences in numpy without hardcoding?
1. **Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.**
2. **a = np.array([1,2,3])**
3. **array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])**

In [67]:
original_array = np.array([1,2,3])
print("Original array:\n", original_array)
print("Custom Sequence Array:",np.hstack((np.repeat(original_array,3), np.tile(original_array, 3))))

Original array:
 [1 2 3]
Custom Sequence Array: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
