## ADD, REMOVE DATA IN NUMPY

**1. Combining arrays**: 
- np.concatenate(): The NumPy `concatenate()` function is an array operation used to join two or more arrays along a specified axis. It is useful for combining datasets, restructuring arrays, and performing data manipulation tasks efficiently.
- Syntax => `np.concatenate((array1, array2))` *OR* `np.concatenate((array1, array2, ...), axis=0)`

There Are 3 more types of np.concatenation:
1. Concatenation Along Rows(`np.concatenate((array1, array2), axis=0)`), 
2. Concatenation Along Columns(`np.concatenate((array1, array2), axis=1)`) 
3. Concatenation of 3D Arrays(`np.concatenate((array1, array2), axis=0)`)
 

In [1]:
import numpy as np

In [14]:
#BASIC CONCATENATION 
array_num = np.array([1,2,3])
array_str = np.array(['one','two','three'])

print("Combining Array with np.concatenate:", np.concatenate((array_num, array_str)))

#CONCATENATION ALONG ROWS:
initial_array = np.array([[1,2],[3,4]])
secondary_array_rows = np.array([[5,6]])

result_rows = np.concatenate((initial_array, secondary_array_rows), axis=0)
print("concatenation along rows combintation:\n", result_rows)

#CONCATENATION ALONG COLUMNS:
secondary_array_columns = np.array([[5,6], [7,8]])
result_columns = np.concatenate((initial_array, secondary_array_columns), axis=1)
print("concatenation along columns combintation:\n", result_columns)

#3D ARRAY CONCATENATION:
array_3d_initial = np.array([[[[1,2],
                              [3,4],]]])

array_3d_secondary = np.array([[[[5,6],
                              [7,8]
                              ]]])
result_3d_array = np.concatenate((array_3d_initial, array_3d_secondary),axis=0)
print("3D array concatenation:\n", result_3d_array)


Combining Array with np.concatenate: ['1' '2' '3' 'one' 'two' 'three']
concatenation along rows combintation:
 [[1 2]
 [3 4]
 [5 6]]
concatenation along columns combintation:
 [[1 2 5 6]
 [3 4 7 8]]
3D array concatenation:
 [[[[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]]]
