## ADD, REMOVE, COMBINING DATA IN NUMPY

**1. Combining arrays**: 
- np.concatenate(): The NumPy `concatenate()` function is an array operation used to join two or more arrays along a specified axis. It is useful for combining datasets, restructuring arrays, and performing data manipulation tasks efficiently.
- Syntax => `np.concatenate((array1, array2))` *OR* `np.concatenate((array1, array2, ...), axis=0)`

There Are 3 more types of np.concatenation:
1. Concatenation Along Rows(`np.concatenate((array1, array2), axis=0)`), 
2. Concatenation Along Columns(`np.concatenate((array1, array2), axis=1)`) 
3. Concatenation of 3D Arrays(`np.concatenate((array1, array2), axis=0)`)
 

In [1]:
import numpy as np

In [2]:
#BASIC CONCATENATION 
array_num = np.array([1,2,3])
array_str = np.array(['one','two','three'])

print("Combining Array with np.concatenate:", np.concatenate((array_num, array_str)))

#CONCATENATION ALONG ROWS:
initial_array = np.array([[1,2],[3,4]])
secondary_array_rows = np.array([[5,6]])

result_rows = np.concatenate((initial_array, secondary_array_rows), axis=0)
print("concatenation along rows combintation:\n", result_rows)

#CONCATENATION ALONG COLUMNS:
secondary_array_columns = np.array([[5,6], [7,8]])
result_columns = np.concatenate((initial_array, secondary_array_columns), axis=1)
print("concatenation along columns combintation:\n", result_columns)

#3D ARRAY CONCATENATION:
array_3d_initial = np.array([[[[1,2],
                              [3,4],]]])

array_3d_secondary = np.array([[[[5,6],
                              [7,8]
                              ]]])
result_3d_array = np.concatenate((array_3d_initial, array_3d_secondary),axis=0)
print("3D array concatenation:\n", result_3d_array)


Combining Array with np.concatenate: ['1' '2' '3' 'one' 'two' 'three']
concatenation along rows combintation:
 [[1 2]
 [3 4]
 [5 6]]
concatenation along columns combintation:
 [[1 2 5 6]
 [3 4 7 8]]
3D array concatenation:
 [[[[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]]]


#### ARRAY COMPATIBILITY(imp):
1. Shape Compatibility: The shape of an array or matrix is defined by the number of rows and columns it has. A shape is considered compatible if the dimensions of the arrays are the same or one of them is one.

**[Understanding Shape and Dimension Compatibility in NumPy](https://www.linkedin.com/pulse/understanding-shape-dimension-compatibility-numpy-can-arslan)**

In [3]:
a = np.array([[1,2,3],['one','two','three']])
b = np.array([[4,5,6],['four','five','six']])

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[1, 1, 1]])


print(a.shape, b.shape, c.shape, d.shape)

print("Compatibility shapes: ", a.shape == b.shape)         #returns true  same dimensions
print("Compatibility shapes: ", a.shape == c.shape)         #returns true same dimensions
print("Compatibility shapes: ", a.shape == d.shape)         #returns false not same dimensions

print("Compatibility shapes: ", b.shape == c.shape)         #returns true same dimensions
print("Compatibility shapes: ", b.shape == d.shape)         #returns false not same dimensions


(2, 3) (2, 3) (2, 3) (1, 3)
Compatibility shapes:  True
Compatibility shapes:  True
Compatibility shapes:  False
Compatibility shapes:  True
Compatibility shapes:  False


#### VSTACK():
vstack() always adds up row. The `np.vstack()` function is used to stack arrays in sequence vertically (row-wise). 

The `vstack()` function is typically used when you want to merge multiple arrays into a single array by stacking them on top of each other. This function requires that the arrays have the same shape along all but the first axis.

*syntax:* `numpy.vstack((array1, array2, ...))`
In this syntax, `vstack()` takes a tuple of arrays and returns a single array by stacking the input arrays vertically.

New Row is added like this=> `np.array([[1,2],[3,4],[5,6][7,8],[9,10]])` Here [7,8],[9,10] are added as a row in each.

In [4]:
#Adding row:
original = np.array([[1,2],[3,4],[5,6]])
new_row = np.array([[7,8],[9,10]])

vstack_new_row = np.vstack((original, new_row))
print("Original Array:\n",original)
print("with Vstack() Array:\n",vstack_new_row)


Original Array:
 [[1 2]
 [3 4]
 [5 6]]
with Vstack() Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


#### HSTACK():
It is used to horizontally stack arrays. It is equivalent to using `concatenate()` along axis 1.

The `hstack()` operation is used when you need to join arrays side by side, provided they have the same shape except along the axis being concatenated. It is particularly useful in data manipulation tasks where merging feature sets is required.

*syntax:* `numpy.hstack((array1, array2, ...))`: In this syntax, `tup` is a tuple or list of arrays to be stacked horizontally. All arrays must have the same shape except for the dimension corresponding to axis 1 (columns).

New Column is added like this=> `np.array([[1,2,7],[3,4,8],[5,6,9]])` Here 7,8,9 are added as a column in each.

In [5]:
#Adding Column:
new_col = np.array([[7],[8],[9]])

vstack_new_col = np.hstack((original, new_col))
print("Original Array:\n",original)
print("with Hstack() Array:\n",vstack_new_col)


Original Array:
 [[1 2]
 [3 4]
 [5 6]]
with Hstack() Array:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


#### NP.DELETE()
The NumPy `delete()` function is used to remove elements from an array along a specified axis. It is a versatile tool for modifying array structures by eliminating unwanted data.

The `delete()` function is commonly used when you need to alter the size of an array by removing specific elements, rows, or columns. It is particularly useful for data cleaning and preprocessing tasks.

Syntax: `np.delete("name of array", index start, index stop, index step)`

In [12]:
array = np.array([1,2,3,4,5])
deleted_array = np.delete(array, 1)
print("Array Before Deletion:", array)
print("Array After Deletion:", deleted_array)


#Deleting Row:
array_row = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_arr = np.delete(array_row, 1, axis=0)
print("Array Before Deleting Row:\n", array)
print("Array after Deleting Row:\n",row_arr)

#Deleting Column:
array_col = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
col_arr = np.delete(array_col, [1, 3], axis=1)
print("Array Before Deleting column:\n", array)
print("Array after deleting column:\n",col_arr)

Array Before Deletion: [1 2 3 4 5]
Array After Deletion: [1 3 4 5]
Array Before Deleting Row:
 [1 2 3 4 5]
Array after Deleting Row:
 [[1 2 3]
 [7 8 9]]
Array Before Deleting column:
 [1 2 3 4 5]
Array after deleting column:
 [[1 3]
 [5 7]]
