# ARRAY PROPERTIES OR ATTRIBUTES

In NumPy, attributes are properties of NumPy arrays that provide information about the array's shape, size, data type, dimension, and so on.

For example, to get the dimension of an array, we can use the ndim attribute.

There are numerous attributes available in NumPy.

1. ndim	— returns number of dimension of the array. It tells you how many axes (dimensions) the array has.

2. size — returns number of elements in the array. This returns a tuple representing the array’s shape — i.e. how many elements are in each dimension.

3. dtype — returns data type of elements in the array. This shows the data type of elements stored in the array(dtype = int64). NumPy automatically chooses the most efficient data type.

4. shape — This returns a tuple representing the array’s shape — i.e. how many elements are in each dimension.

5. itemsize	— returns the size (in bytes) of each elements in the array. It gives the number of bytes used by each element in the array.

6. data — returns the buffer containing actual elements of the array in memory.

7. nbytes — Total Memory Used by Array It gives the total memory consumed by all elements.

8. .T — Transpose of Matrix: This flips rows and columns. Transpose is widely used in matrix algebra and data manipulation.

In [1]:
import numpy as np

In [9]:
array = np.array([[1,2,3],
                  [4,5,6]])
print("Array:\n",array)

#ndim
print(f"Dimension Attribute:{array.ndim}")
print("\n")

#size
print(f"Size Attribute:{array.size}")
print("\n")

#dtype
print(f"Data Type Attribute:{array.dtype}")
print("\n")

#shape
print(f"Shape Attribute:{array.shape}")
print("\n")

#itemsize
print("Item size:", array.itemsize, "bytes")
print("\n")

#data
print(f"Data Attribute:{array.data}")
print("\n")

#.nbytes
print("Total memory consumed by all elements: ", array.nbytes, "bytes")
print("\n")

#.T Transpose of Matrix
print("Original:\n", array)
print("Transpose:\n", array.T)



Array:
 [[1 2 3]
 [4 5 6]]
Dimension Attribute:2


Size Attribute:6


Data Type Attribute:int64


Shape Attribute:(2, 3)


Item size: 8 bytes


Data Attribute:<memory at 0x000001445E4672A0>


Total memory consumed by all elements:  48 bytes


Original:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
