# NUMPY ARRAY OPERATIONS, INDEXING, SLICING

### ARRAY OPERATIONS:
NumPy can perform element-wise mathematical operations directly on arrays — without using loops.
This is called vectorization, and it makes computations much faster (thanks to C-level optimization).
#### 💡Real-World Use Cases

1. Data Normalization:	Divide all image pixels by 255 using image / 255.0
2. Finance:            	Calculate daily stock returns with (new_prices - old_prices) / old_prices
3. Machine Learning:	Apply activation functions (like ReLU, sigmoid) to all neurons using vectorized operations
4. Physics/Engineering:	Compute velocities, forces, or temperature gradients efficiently

### INDEXING(Accessing Elements): 
Indexing allows you to access or modify specific elements of a NumPy array.
Similar to lists — but faster and more powerful (supports multi-dimensional access).
#### 💡Real-World Use Cases:
1. Image Processing:	        Access pixel [row, column] from an image matrix.

2. Data Analysis:	            Get the value of a specific column and row in a dataset.

3. Simulations:             	Access elements from a 3D simulation grid (like temperature at a specific point).

### SLICING(Extracting Subarrays):
Slicing allows selecting a range of elements or subarrays using the syntax: 
array[start:end:step]

Just like Python lists, but supports multi-dimensional slicing.
#### 💡Real-World Use Cases:
 Real-World Use Cases

1. Image Cropping:	        image[100:200, 50:150] → crop specific region.
2. Data Selection:	        Select first 100 rows of a dataset: data[:100, :].
3. Time Series Analysis:	Select last 7 days of stock data: prices[-7:].
4. Batch Processing:     	Split data into chunks: data[i:i+batch_size]

### Boolean Indexing (Conditional Selection):
Filter data by condition.
#### 💡Real-World Use Cases:
1. Filtering Data:          Extract all temperatures above 100°C.
2. Model Training:          Select only samples with valid labels.
3. Finance:                 Find all days where stock returns > 0.

In [1]:
import numpy as np

In [2]:
#BASIC INDEXING / SLICING ON 1D ARRAY
array = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing: ", array[1:5])    #will start from 2 till 5
print("With Step Slicing: ", array[1:8:2])  #will start from 2 till 8 with skiping a value as step.
print("Negative Slicing: ", array[-1])      #will start from ending all the way till -1 value. 

Basic Slicing:  [2 3 4 5]
With Step Slicing:  [2 4 6 8]
Negative Slicing:  10


In [3]:
#INDEXING / SLICING ON 2D ARRAY
array_2d = np.array([['one','two','three'],
                     ['four','five','six'],
                     ['seven','eight','nine']
                     ])

#Syntax: name_of_array[row,column]
print("Targeting specific element at specific position:", array_2d[1,2])
print("Targeting Entire Row:", array_2d[1])         #will return 'four','five','six'
print("Targeting Entire Column:", array_2d[:,2])    #syntax: name_of_array[:, column]. will return 'three','six','nine'
print("Targeting Last Element:",array_2d[-1, -1]) # 'nine' (last element)


Targeting specific element at specific position: six
Targeting Entire Row: ['four' 'five' 'six']
Targeting Entire Column: ['three' 'six' 'nine']
Targeting Last Element: nine


In [4]:
#Boolean Indexing:
temp_array = np.array([[90,100,110],
                       [55,190,200],
                       [78,99,140]
                       ])
extracted_array = temp_array[temp_array < 100]
print("Extracting all Temperatures below 100C:\n", extracted_array)


Extracting all Temperatures below 100C:
 [90 55 78 99]


#### Sorting:
Sorting arrays in NumPy is useful for organizing data, preparing it for further analysis, or improving the efficiency of other operations.
NumPy's array sorting capabilities are used to reorder elements within an array to facilitate data organization or analysis.

1. Basic Method: np.sort("name of array") returns a sorted copy of an array — it does not change the original array (unlike Python’s list.sort()).

2. 2D array Sort: For 2D or higher arrays, you can sort along a specific axis: 
axis=0 → sort column-wise. This will be used mostly because in data science tabular data, we go top to bottom in data sheet.
axis=1 → sort row-wise.
`Syntax: np.sort("name of array", axis(0 or 1))`
3. Sorting in Descending Order: sorts the array in ascending order and then reverses it to achieve descending order. `syntax: np.sort("name of array")[::-1]`

💡 Real-World Use Cases

- **Data Cleaning**:	Sort values to detect outliers or missing trends
- **ML Ranking**:	Sort predictions, probabilities, or feature importances
- **Finance**:	Sort stocks by performance or prices
- **Image Processing**:	Sort pixel intensity values for thresholding or contrast
- **Leaderboards**:	Sort scores or ranks of participants

In [14]:
unsorted_array = np.array([10,99,23,432,13,12,3,2,1,5,66,43,232,54,65,4,18,28])
print("Basic np.sort():", np.sort(unsorted_array))
print("Descending Order Sorting:",np.sort(unsorted_array)[::-1])


unsorted_array_2d = np.array([
    [3,2], [9,8],[28,5],[18,8],[2005,2004]
    ])

print("ORIGINAL UNSORTED 2D ARRAY:\n", unsorted_array_2d)
print("Sorted 2D array by Column(axis0):\n", np.sort(unsorted_array_2d,axis=0))
print("Sorted 2D array by Row(axis1):\n", np.sort(unsorted_array_2d,axis=1))


Basic np.sort(): [  1   2   3   4   5  10  12  13  18  23  28  43  54  65  66  99 232 432]
Descending Order Sorting: [432 232  99  66  65  54  43  28  23  18  13  12  10   5   4   3   2   1]
ORIGINAL UNSORTED 2D ARRAY:
 [[   3    2]
 [   9    8]
 [  28    5]
 [  18    8]
 [2005 2004]]
Sorted 2D array by Column(axis0):
 [[   3    2]
 [   9    5]
 [  18    8]
 [  28    8]
 [2005 2004]]
Sorted 2D array by Row(axis1):
 [[   2    3]
 [   8    9]
 [   5   28]
 [   8   18]
 [2004 2005]]
