# NUMPY ARRAY OPERATIONS, INDEXING, SLICING

### ARRAY OPERATIONS:
NumPy can perform element-wise mathematical operations directly on arrays — without using loops.
This is called vectorization, and it makes computations much faster (thanks to C-level optimization).
#### 💡Real-World Use Cases

1. Data Normalization:	Divide all image pixels by 255 using image / 255.0
2. Finance:            	Calculate daily stock returns with (new_prices - old_prices) / old_prices
3. Machine Learning:	Apply activation functions (like ReLU, sigmoid) to all neurons using vectorized operations
4. Physics/Engineering:	Compute velocities, forces, or temperature gradients efficiently

### INDEXING(Accessing Elements): 
Indexing allows you to access or modify specific elements of a NumPy array.
Similar to lists — but faster and more powerful (supports multi-dimensional access).
#### 💡Real-World Use Cases:
1. Image Processing:	        Access pixel [row, column] from an image matrix.

2. Data Analysis:	            Get the value of a specific column and row in a dataset.

3. Simulations:             	Access elements from a 3D simulation grid (like temperature at a specific point).

### SLICING(Extracting Subarrays):
Slicing allows selecting a range of elements or subarrays using the syntax: 
array[start:end:step]

Just like Python lists, but supports multi-dimensional slicing.
#### 💡Real-World Use Cases:
 Real-World Use Cases

1. Image Cropping:	        image[100:200, 50:150] → crop specific region.
2. Data Selection:	        Select first 100 rows of a dataset: data[:100, :].
3. Time Series Analysis:	Select last 7 days of stock data: prices[-7:].
4. Batch Processing:     	Split data into chunks: data[i:i+batch_size]

### Boolean Indexing (Conditional Selection):
Filter data by condition.
#### 💡Real-World Use Cases:
1. Filtering Data:          Extract all temperatures above 100°C.
2. Model Training:          Select only samples with valid labels.
3. Finance:                 Find all days where stock returns > 0.

In [1]:
import numpy as np

In [2]:
#BASIC INDEXING / SLICING ON 1D ARRAY
array = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing: ", array[1:5])    #will start from 2 till 5
print("With Step Slicing: ", array[1:8:2])  #will start from 2 till 8 with skiping a value as step.
print("Negative Slicing: ", array[-1])      #will start from ending all the way till -1 value. 

Basic Slicing:  [2 3 4 5]
With Step Slicing:  [2 4 6 8]
Negative Slicing:  10


In [3]:
#INDEXING / SLICING ON 2D ARRAY
array_2d = np.array([['one','two','three'],
                     ['four','five','six'],
                     ['seven','eight','nine']
                     ])

#Syntax: name_of_array[row,column]
print("Targeting specific element at specific position:", array_2d[1,2])
print("Targeting Entire Row:", array_2d[1])         #will return 'four','five','six'
print("Targeting Entire Column:", array_2d[:,2])    #syntax: name_of_array[:, column]. will return 'three','six','nine'
print("Targeting Last Element:",array_2d[-1, -1]) # 'nine' (last element)


Targeting specific element at specific position: six
Targeting Entire Row: ['four' 'five' 'six']
Targeting Entire Column: ['three' 'six' 'nine']
Targeting Last Element: nine


In [4]:
#Boolean Indexing:
temp_array = np.array([[90,100,110],
                       [55,190,200],
                       [78,99,140]
                       ])
extracted_array = temp_array[temp_array < 100]
print("Extracting all Temperatures below 100C:\n", extracted_array)


Extracting all Temperatures below 100C:
 [90 55 78 99]


#### Sort():
Sorting arrays in NumPy is useful for organizing data, preparing it for further analysis, or improving the efficiency of other operations.
NumPy's array sorting capabilities are used to reorder elements within an array to facilitate data organization or analysis.

1. Basic Method: np.sort("name of array") returns a sorted copy of an array — it does not change the original array (unlike Python’s list.sort()).

2. 2D array Sort: For 2D or higher arrays, you can sort along a specific axis: 
axis=0 → sort column-wise. This will be used mostly because in data science tabular data, we go top to bottom in data sheet.
axis=1 → sort row-wise.
`Syntax: np.sort("name of array", axis(0 or 1))`
3. Sorting in Descending Order: sorts the array in ascending order and then reverses it to achieve descending order. `syntax: np.sort("name of array")[::-1]`

💡 Real-World Use Cases

- **Data Cleaning**:	Sort values to detect outliers or missing trends
- **ML Ranking**:	Sort predictions, probabilities, or feature importances
- **Finance**:	Sort stocks by performance or prices
- **Image Processing**:	Sort pixel intensity values for thresholding or contrast
- **Leaderboards**:	Sort scores or ranks of participants

In [5]:
unsorted_array = np.array([10,99,23,432,13,12,3,2,1,5,66,43,232,54,65,4,18,28])
print("Basic np.sort():", np.sort(unsorted_array))
print("Descending Order Sorting:",np.sort(unsorted_array)[::-1])


unsorted_array_2d = np.array([
    [3,2], [9,8],[28,5],[18,8],[2005,2004]
    ])

print("ORIGINAL UNSORTED 2D ARRAY:\n", unsorted_array_2d)
print("Sorted 2D array by Column(axis0):\n", np.sort(unsorted_array_2d,axis=0))
print("Sorted 2D array by Row(axis1):\n", np.sort(unsorted_array_2d,axis=1))


Basic np.sort(): [  1   2   3   4   5  10  12  13  18  23  28  43  54  65  66  99 232 432]
Descending Order Sorting: [432 232  99  66  65  54  43  28  23  18  13  12  10   5   4   3   2   1]
ORIGINAL UNSORTED 2D ARRAY:
 [[   3    2]
 [   9    8]
 [  28    5]
 [  18    8]
 [2005 2004]]
Sorted 2D array by Column(axis0):
 [[   3    2]
 [   9    5]
 [  18    8]
 [  28    8]
 [2005 2004]]
Sorted 2D array by Row(axis1):
 [[   2    3]
 [   8    9]
 [   5   28]
 [   8   18]
 [2004 2005]]


#### Filter:
Filtering in NumPy means selecting elements based on conditions. Filtering arrays in NumPy allows you to extract elements that meet certain criteria, enabling data analysis and manipulation. This is particularly useful in preparing data for machine learning or statistical analysis.

**MASK**: A mask in NumPy is simply an expression that evaluates to True or False for every element in an array. You write a condition → NumPy checks it for each element → returns a boolean array.
That boolean array is called a mask.Mask is condition applied element-wise → gives True/False → used to pick values.

1. Basic Filtering: `syntax: array = np.array([array])` => `filtered_array = array([condition])`.
2. Filtering with Multiple Condition: `& for AND, | for OR, ~ for NOT`
3. Boolean Filtering: When you apply a condition to a NumPy array, NumPy returns a Boolean mask.

💡 Real-World Use Cases(very important)

- **ML Data Cleaning**:	Remove missing values, outliers, negatives
- **Recommendation Systems**	Filter users/products with specific conditions
- **Finance**:	Filter stock prices above/below thresholds
- **Image Processing**	Select pixels > some intensity
- **Statistics**	Select data in a specific range to find mean/median

In [6]:
numbers = np.array([1,2,3,4,5,54,3,2,123,434,3,99,90,100,99,1828])

#Basic Filter
even_numbers_array = numbers[numbers % 2 == 0]
print("Even Numbers Array: ", even_numbers_array)

#Multiple Condition Filter
multi_condition_array = (numbers > 50) & (numbers < 500)
filtered_array = numbers[multi_condition_array]
print("Multiple Condition Array. Number Greater than 50 and Less than 500:", filtered_array)

#Boolean Filtering or MASK:
mask = multi_condition_array
print("Mask Will Return Boolean Array for Multiple Condition Array: ", mask)

Even Numbers Array:  [   2    4   54    2  434   90  100 1828]
Multiple Condition Array. Number Greater than 50 and Less than 500: [ 54 123 434  99  90 100  99]
Mask Will Return Boolean Array for Multiple Condition Array:  [False False False False False  True False False  True  True False  True
  True  True  True False]


#### FANCY INDEXING VS np.where():

**1.FANCY INDEXING:**
Direct Index-Based Selection
Fancy indexing means: Selecting elements using a list/array of indices. Fancy indexing does NOT check any condition.
It directly picks elements from given index positions.

**2.NP.WHERE()**: NumPy's np.where is a versatile function for conditional operations on arrays. It checks a condition and returns either indices or values based on it. Great for vectorized (fast, no-loops) operations.
The use of np.where provides more flexibility by returning the indices of elements that meet the condition, which can then be used for further operations. Simply its a DETECTOR function → finds locations based on condition.

The use of np.where provides more flexibility by returning the indices of elements that meet the condition, which can then be used for further operations.
**Syntax:**
1. Indices mode: ```np.where(condition)```  Returns a tuple of arrays with indices where condition is True.  
Example: For a 1D array, returns one array of indices.

2. Replacement mode: ```np.where(condition, x, y)```  Where condition is True, take from x; else from y.  
x and y can be arrays or scalars; must broadcast to the shape of condition.


**USE CASES**:
Use Fancy Indexing when:
- You already know which positions to pick
- You want specific rows/columns from arrays
- You're selecting arbitrary element positions

**USE CASES**:
Use np.where() when:
- Takes a condition as input(find all values > 100).
- Returns indices instead of elemets.
- You want to Find positions.


In [7]:
#FANCY INDEXING:
#indices refers to the positions of elements that satisfy the condition
indices = [0,5,7]           #here 0,5,7 are position for an array called as indices.
print("Indices of an array:", numbers[indices])

#NP.WHERE(): 
where_result = np.where(numbers > 10)
print(where_result)     
print("np.where() function applied on numbers array: ", numbers[where_result])

Indices of an array: [ 1 54  2]
(array([ 5,  8,  9, 11, 12, 13, 14, 15]),)
np.where() function applied on numbers array:  [  54  123  434   99   90  100   99 1828]


#### CONDITIONAL ARRAY WITH NP.WHERE():
Vectorized IF-ELSE operation.

`Syntax: np.where(condition, x, y)`
- *condition*:  `condition` is a boolean array.
- *x,y*: `x` and `y` are optional arrays.
- When only `condition` is provided, `where()` returns the indices of elements where `condition` is `True`.

Think of it as Python if-else clause, it means: 
 `if(condition):`
    `print(x)`
    `else:`
        `print(y)`

In [12]:
condition_array = np.where(numbers > 10, True, False)
print("Numbers Array: ",numbers)
print("Conditional array with np.where() Numbers Greater than 10: ",condition_array)

Numbers Array:  [   1    2    3    4    5   54    3    2  123  434    3   99   90  100
   99 1828]
Conditional array with np.where() Numbers Greater than 10:  [False False False False False  True False False  True  True False  True
  True  True  True  True]
