# ARRAY PROPERTIES OR ATTRIBUTES

In NumPy, attributes are properties of NumPy arrays that provide information about the array's shape, size, data type, dimension, and so on.

For example, to get the dimension of an array, we can use the ndim attribute.

There are numerous attributes available in NumPy.

1. ndim	— returns number of dimension of the array. It tells you how many axes (dimensions) the array has.

2. size — returns number of elements in the array. This returns a tuple representing the array’s shape — i.e. how many elements are in each dimension.

3. dtype — returns data type of elements in the array. This shows the data type of elements stored in the array(dtype = int64). NumPy automatically chooses the most efficient data type.

4. shape — This returns a tuple representing the array’s shape — i.e. how many elements are in each dimension.

5. itemsize	— returns the size (in bytes) of each elements in the array. It gives the number of bytes used by each element in the array. Each element takes 8 bytes (for int64).
Smaller types like int8 take 1 byte — helps in memory optimization.

6. data — returns the buffer containing actual elements of the array in memory.

7. nbytes — Total Memory Used by Array It gives the total memory consumed by all elements.

8. .T — Transpose of Matrix: This flips rows and columns. Transpose is widely used in matrix algebra and data manipulation.

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],
                  [4,5,6]])
print("Array:\n",array)

#ndim
print(f"Dimension Attribute:{array.ndim}")
print("\n")

#size
print(f"Size Attribute:{array.size}")
print("\n")

#dtype
print(f"Data Type Attribute:{array.dtype}")
print("\n")

#shape
print(f"Shape Attribute:{array.shape}")
print("\n")

#itemsize
print("Item size:", array.itemsize, "bytes")
print("\n")

#data
print(f"Data Attribute:{array.data}")
print("\n")

#.nbytes
print("Total memory consumed by all elements: ", array.nbytes, "bytes")
print("\n")

#.T Transpose of Matrix
print("Original:\n", array)
print("Transpose:\n", array.T)



Array:
 [[1 2 3]
 [4 5 6]]
Dimension Attribute:2


Size Attribute:6


Data Type Attribute:int64


Shape Attribute:(2, 3)


Item size: 8 bytes


Data Attribute:<memory at 0x0000016956018A00>


Total memory consumed by all elements:  48 bytes


Original:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


## PRACTICE TASK

Create a 3D array and print all of these attributes.

Change data type to float32 and observe how .itemsize and .nbytes change.

Print .T for 2D and 3D arrays — see how transposition behaves differently.

In [3]:
attribute_array = np.array([[[10,20,30]],
                            [[40,50,60]],
                            [[70,80,90]],
                            ])
#converting array to float32    #.astype(np.float32) → actually converts each element to 32-bit float.
attribute_array = attribute_array.astype(np.float32)

print(attribute_array)
print("Item Size of Array:", attribute_array.itemsize)
print("Number of bytes of Array:", attribute_array.nbytes)


[[[10. 20. 30.]]

 [[40. 50. 60.]]

 [[70. 80. 90.]]]
Item Size of Array: 4
Number of bytes of Array: 36


### ARRAY RESHAPING
Reshaping means changing the shape (dimensions) of an existing NumPy array without changing its data.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

1. Basic Reshape: Reshape From 1-D to 2-D. Reshaped them into a 3×4 matrix.

2. 3D Reshape: instead of ((3,4)), give ((2,2,3))

3. Flattenening an Array: If you want to convert a multi-dimensional array back to 1D, use .ravel() or .flatten() methods. 
                          .ravel() returns a copy.      .flatten() returns a view(more memory efficient)

4. Transpose an Array: This flips rows and columns. Transpose is widely used in matrix algebra and data manipulation.

In [4]:
original_array = np.arange(12)
print(f"Original Array:",original_array)

reshaped = original_array.reshape((3,4))
print("\nReshaped Array(3x4): \n", reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array: ", flattened) #flattened the reshaped array

#Ravel (returns view, instead of copy)

raveled = reshaped.ravel()
print("\n Raveled Array: ", raveled) #flattened the reshaped array

automatic_array = original_array.reshape(3, -1)
print("\n3 Rows given manually, columns calculated automatically: \n",automatic_array)


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array(3x4): 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

3 Rows given manually, columns calculated automatically: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### PRACTICE TASK 

🧩 Practice Tasks

Create an array from 1–15 and reshape it into:

(3, 5)

(5, 3)

Reshape it into a 3D tensor of shape (5, 3, 1).

Flatten a 3×3 matrix using both .ravel() and .flatten().

Use -1 to automatically infer missing dimensions.

In [14]:
array = np.arange(15)

reshape_array_one = array.reshape(3,5)
print("Reshaped into (3, 5): \n",reshape_array_one)

reshape_array_two = array.reshape(5,3)
print("Reshaped into (5, 3): \n",reshape_array_two)

reshaped_tensor = array.reshape(5,3,1)
print("Reshaped Tensor:\n", reshaped_tensor)

array_two = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print("3x3 matrix:\n",array_two)

flattenend_array = array_two.flatten()
print("Flatened 3x3 using flatten(): \n",flattenend_array)

raveled_array = array_two.ravel()
print("Raveled 3x3 using ravel(): \n",raveled_array)

auto_array_dimension = array.reshape(3, -1)
print("-1 method implemented array: \n", auto_array_dimension)
 

Reshaped into (3, 5): 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Reshaped into (5, 3): 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Reshaped Tensor:
 [[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]]]
3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flatened 3x3 using flatten(): 
 [1 2 3 4 5 6 7 8 9]
Raveled 3x3 using ravel(): 
 [1 2 3 4 5 6 7 8 9]
-1 method implemented array: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
