## NumPy Arrays and Basics
Getting Started with Numpy Basics

In [1]:
import numpy as np
import time as tm

Creating Array from list


In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.__version__)


2.2.6


## LIST VS NUMPY ARRAYS
Multiplication difference

In [4]:
py_list = [18, 28] * 2
print("Python List multiplied by 2:", py_list)      # Python list multiplication duplicates the list

np_array = np.array([18, 28]) * 2
print("NumPy Array multiplied by 2:", np_array)     # NumPy array multiplication scales each element


Python List multiplied by 2: [18, 28, 18, 28]
NumPy Array multiplied by 2: [36 56]


numpy.arange(start, stop, step):
Generates values starting from start up to (but not including) stop, with the specified step size.

In [ ]:
start_time = tm.time()

py_list = [i*2 for i in range(1000000)]
print("Python list execution time:", tm.time() - start_time)

start_time = tm.time()
np_array = np.arange(1000000) * 2
print("NumPy array execution time:", tm.time() - start_time)



Python list execution time: 0.04375743865966797
NumPy array execution time: 0.0030410289764404297
