## NumPy Arrays and Basics
Getting Started with Numpy Basics

#### MATRIX & VECTORS DEFINITION.
- For matrices, dimension refers to the number of rows and columns, expressed as *m x n*. 
- For vectors, dimension is the number of components in the list, indicating how many elements are in it.

##### Matrix Dimension:
- where *m* is the number of rows and *n* is the number of columns.
- The dimension is crucial for determining if matrices can be added, subtracted, or multiplied. 
- *Example:* A matrix with 3 rows and 2 columns is a *3 x 2* matrix.

##### Vector Dimension: 
- A vector with three components, such as *(x,y,z)*, is a 3-dimensional vector. 
- A vector with two components, like *(x,y)*, is a 2-dimensional vector.
- Vectors can be represented as matrices with a single row (row vector) or a single column (column vector).
- *For example*, a row vector with three elements is a *1 x 3* matrix, and a column vector with three elements is a *(3 x 1)* matrix. 

In [1]:
import numpy as np
import time as tm

Creating Array from list


In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.__version__)


2.2.6


## LIST VS NUMPY ARRAYS
Multiplication difference

In [4]:
py_list = [18, 28] * 2
print("Python List multiplied by 2:", py_list)      # Python list multiplication duplicates the list

np_array = np.array([18, 28]) * 2
print("NumPy Array multiplied by 2:", np_array)     # NumPy array multiplication scales each element


Python List multiplied by 2: [18, 28, 18, 28]
NumPy Array multiplied by 2: [36 56]


numpy.arange(start, stop, step):
Generates values starting from start up to (but not including) stop, with the specified step size.

In [5]:
start_time = tm.time()

py_list = [i*2 for i in range(1000000)]
print("Python list execution time:", tm.time() - start_time)

start_time = tm.time()
np_array = np.arange(1000000) * 2
print("NumPy array execution time:", tm.time() - start_time)



Python list execution time: 0.03804206848144531
NumPy array execution time: 0.002350330352783203


# Vectorization
In NumPy, you can apply mathematical operations directly to arrays — no need for loops.This is called vectorized operation, and it’s one of the biggest reasons NumPy is used in Data Science.

In [6]:
numbers = np.array([2,4,6,8,10])
print("Original array:", numbers)

multiplication = numbers * 3
print("Multiplication by 3:", multiplication)

addition = numbers + 10
print("Addition of 10:", addition)

square = numbers ** 2
print("Square of elements:", square)

Original array: [ 2  4  6  8 10]
Multiplication by 3: [ 6 12 18 24 30]
Addition of 10: [12 14 16 18 20]
Square of elements: [  4  16  36  64 100]


## Creating Arrays from Scratch
1. np.zeros(): Create an array of zeros
2. np.ones(): Create an array of ones
3. np.full(): Create a constant array
4. np.arange(): Create an array of evenly spaced values. Similar to Range() func in Python.
5. np.linspace(): Create an array of evenlyspaced values (number of samples)


In [33]:
#np.zeros()
zeros_matrix = np.zeros((3,4))      #here 3 is for rows, and 4 is for columns.
print(f"Zeros Array: \n{zeros_matrix}")

#np.ones()
ones_matrix = np.ones((3,3))        #here 3rows,3 columns. The `ones()` function is used when you need an array of a specific shape filled with the value `1`
print(f"Ones Array: \n{ones_matrix}")

#np.full()
full_matrix = np.full((3,3), 7)     #Here 3rows,3 columns. You can fill an array with any constant number(where 7 is)
print(f"Full Array: \n {full_matrix}")

#np.arange(): It is also called sequence array.
arange_array = np.arange(10,110,10)     #np.arange(start, stop, step)
print(f"arange() arrays/sequence arrays: {arange_array}")    #will return from 10 to 100

#np.linspace()          #generate an array of evenly spaced numbers over a specified interval.
linspace_array = np.linspace(0,110,10)
print(f"linspace() function array: \n{linspace_array}")



Zeros Array: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
arange() arrays/sequence arrays: [ 10  20  30  40  50  60  70  80  90 100]
linspace() function array: 
[  0.          12.22222222  24.44444444  36.66666667  48.88888889
  61.11111111  73.33333333  85.55555556  97.77777778 110.        ]


## Creating Arrays from Scratch: Random module

1 np.random(): Create an array with random values.

2. np.random.randint(): creates an array with Random integers
3. np.random.randint(): Creates an array with Random Float

In [ ]:
#Random Arrays: #Create an array with random values.      IMPORTANT! 
Random_array = np.random.random((3,4))
print(f"Random Array: \n{Random_array}")
print("\n")

#random.randint : Random integers
rand_int = np.random.randint(10, 100, size=(3, 4))
print(f"random Integers Array: \n{rand_int}")

print("\n")

#random.rand: Random Float
rand_float = np.random.rand(3,3)
print(f"random floats array: \n{rand_float}")

Random Array: 
[[0.35948465 0.45772671 0.30425282 0.73087802]
 [0.15009144 0.9840301  0.87594124 0.41398797]
 [0.85624671 0.02758851 0.25637515 0.36182505]]


random Integers Array: 
[[87 56 47 29]
 [26 13 34 87]
 [81 60 59 14]]


random floats array: 
[[0.96149796 0.67511077 0.92867288]
 [0.55117701 0.62465267 0.14390213]
 [0.61059313 0.61791394 0.03566629]]


# Identity Matrix
In NumPy, an identity matrix is a square matrix with ones on its main diagonal and zeros everywhere else. It acts as the multiplicative identity in matrix operations. You can create an identity matrix in NumPy using two primary functions: numpy.identity() and numpy.eye().

Diagonal elements are all 1s.
Non-diagonal elements are all 0s.

In [49]:
identity_matrix_eye = np.eye(3) 
print(f"Identity Matrix with default property(float): \n{identity_matrix_eye}")

#OR
identity_matrix_identity = np.identity(3, dtype=int)
print(f"Identity Matrix with optional property(dtype = int): \n{identity_matrix_identity}")


Identity Matrix with default property(float): 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity Matrix with optional property(dtype = int): 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


# PRACTICE TASK:
1. A 4×4 array filled with 9s.
2. A random integer matrix of shape (3, 5) between 10 and 99.
3. A 1D array of 10 evenly spaced numbers between 100 and 200.
4. An identity matrix of size 5×5.

In [57]:
#Q1.
q1 = np.full((3,3), 9)    
print(f"A 4x4 array filled with 9s: \n {q1}")
print("\n")

#Q2.
q2 = np.random.randint(10,99, size=(3,5))
print(f"Random Integer Matrix: \n {q2}")
print("\n")

#Q3.
q3 = np.arange(100,200,10)
print(f"1D array: \n{q3}")
print("\n")

#Q4. 
q4 = np.identity(5)
print(f"Identity Matrix of 5x5: \n{q4}")

A 4x4 array filled with 9s: 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]


Random Integer Matrix: 
 [[64 25 27 19 50]
 [41 39 58 75 43]
 [94 23 66 54 98]]


1D array: 
[100 110 120 130 140 150 160 170 180 190]


Identity Matrix of 5x5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
