## NumPy Arrays and Basics
Getting Started with Numpy Basics

In [1]:
import numpy as np
import time as tm

Creating Array from list


In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.__version__)


2.2.6


## LIST VS NUMPY ARRAYS
Multiplication difference

In [4]:
py_list = [18, 28] * 2
print("Python List multiplied by 2:", py_list)      # Python list multiplication duplicates the list

np_array = np.array([18, 28]) * 2
print("NumPy Array multiplied by 2:", np_array)     # NumPy array multiplication scales each element


Python List multiplied by 2: [18, 28, 18, 28]
NumPy Array multiplied by 2: [36 56]


numpy.arange(start, stop, step):
Generates values starting from start up to (but not including) stop, with the specified step size.

In [5]:
start_time = tm.time()

py_list = [i*2 for i in range(1000000)]
print("Python list execution time:", tm.time() - start_time)

start_time = tm.time()
np_array = np.arange(1000000) * 2
print("NumPy array execution time:", tm.time() - start_time)



Python list execution time: 0.03804206848144531
NumPy array execution time: 0.002350330352783203


# Vectorization
In NumPy, you can apply mathematical operations directly to arrays — no need for loops.This is called vectorized operation, and it’s one of the biggest reasons NumPy is used in Data Science.

In [6]:
numbers = np.array([2,4,6,8,10])
print("Original array:", numbers)

multiplication = numbers * 3
print("Multiplication by 3:", multiplication)

addition = numbers + 10
print("Addition of 10:", addition)

square = numbers ** 2
print("Square of elements:", square)

Original array: [ 2  4  6  8 10]
Multiplication by 3: [ 6 12 18 24 30]
Addition of 10: [12 14 16 18 20]
Square of elements: [  4  16  36  64 100]


## Creating Arrays from Scratch

In [ ]:
#np.zeros()
zeros_matrix = np.zeros((3,4))      #here 3 is for rows, and 4 is for columns.
print(f"Zeros Array: \n{zeros_matrix}")

#np.ones()
ones_matrix = np.ones((3,3))        #here 3rows,3 columns. The `ones()` function is used when you need an array of a specific shape filled with the value `1`
print(f"Ones Array: \n{ones_matrix}")

#np.full()
full_matrix = np.full((3,3), 7)     #Here 3rows,3 columns. You can fill an array with any constant number(where 7 is)
print(f"Full Array: \n {full_matrix}")

#np.arange()
arange_array = np.arange(10,110,10)     #np.arange(start, stop, step)
print(f"arange() arrays: {arange_array}")    #will return from 10 to 100

#np.linspace()          #generate an array of evenly spaced numbers over a specified interval.
linspace_array = np.linspace(0,110,10)
print(f"linspace() function array: \n{linspace_array}")


#Random Arrays: #Create an array with random values.      IMPORTANT! 
random_array = np.random.random((3,4))
print(f"Random Array: \n{random_array}")

Zeros Array: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
arange() arrays: [ 10  20  30  40  50  60  70  80  90 100]
linspace() function array: 
[  0.          12.22222222  24.44444444  36.66666667  48.88888889
  61.11111111  73.33333333  85.55555556  97.77777778 110.        ]
