## BROADCAST() IN NUMPY.
- **NumPy broadcasting** is a mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes. It enables the element-wise operation of arrays without making unnecessary copies of data, thereby enhancing performance and memory efficiency.

- **Broadcasting Rules** Broadcasting follows specific rules to determine compatibility:

1. Two dimensions are compatible for broadcasting if they are equal or if one of them is 1.
2. Arrays are treated as if they have the shape of the maximum dimensions by "stretching" the smaller dimension with a size of 1 to match.
3. If the arrays do not satisfy these rules, a ValueError is raised indicating incompatible shapes.
![Broadcasting visualization](array.jpg)

**🧠 When to Use Broadcasting?**
- ✔ Replacing loops
- ✔ Vector math
- ✔ Matrix operations
- ✔ Scaling rows/columns
- ✔ Centering datasets

- Broadcasting is particularly useful in data normalization processes, such as subtracting the mean of each column from the dataset to center the data.


#### Tips and Best Practices
- **Understand shapes:** Always check the shapes of your arrays using .shape to predict how they will broadcast.
- **Leverage broadcasting for efficiency:** Use broadcasting to minimize memory usage and avoid creating unnecessary array copies.
- **Check compatibility:** Ensure your arrays are compatible for broadcasting to avoid runtime errors like ValueError.
- **Use numpy functions:** Utilize built-in NumPy functions which are optimized for broadcasting.
- **Beware of unintended broadcasting:** Always validate results as automatic broadcasting can lead to unexpected results if not thoroughly understood.

In [3]:
import numpy as np

In [ ]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],    # STUDENT BIRYANI
    [2, 120000, 140000, 160000, 190000],    # CHINESE RESTAURANT
    [3, 180000, 230000, 240000, 270000],    # PIZZA MAX
    [4, 200000, 210000, 240000, 270000],    # JARDIN CAFE
    [5, 165000, 176000, 380000, 295000]     # COCONUT GROVE CAFE
    ])
print(sales_data[:, 1:])


#Monthly Average using Broadcast()
monthly_avg_sales = sales_data[:, 1:] / 12
print("\nMonthly Sales Average:\n", monthly_avg_sales.astype(int))      #used .astype to print in integer instead of float.


#Broadcasting() with different dimensions
# Vectorization + broadcasting

sales_data_percentage = sales_data[:, 1:] / np.sum(sales_data[:, 1:], axis=0) * 100
sales_data_percentage.astype(int)
print("Percentage wise sales data:\n", sales_data_percentage)


[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [180000 230000 240000 270000]
 [200000 210000 240000 270000]
 [165000 176000 380000 295000]]

Monthly Sales Average:
 [[12500 15000 18333 20833]
 [10000 11666 13333 15833]
 [15000 19166 20000 22500]
 [16666 17500 20000 22500]
 [13750 14666 31666 24583]]
Percentage wise sales data:
 [[18.40490798 19.23076923 17.74193548 19.60784314]
 [14.72392638 14.95726496 12.90322581 14.90196078]
 [22.08588957 24.57264957 19.35483871 21.17647059]
 [24.5398773  22.43589744 19.35483871 21.17647059]
 [20.24539877 18.8034188  30.64516129 23.1372549 ]]
[[1 0 0 4 4]
 [2 0 8 4 4]
 [3 0 8 0 0]
 [4 8 0 0 0]
 [5 0 8 8 4]]
