In [1]:
import numpy as np
import matplotlib.pyplot as plt

- The following arrays are only saved in memory till python program is running. Once Program gones, arrays gone.
- We can save it in flat files, which includes database

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.random.rand(3, 3)
array3 = np.zeros((4,4))


[[1 2 3]
 [4 5 6]] [[0.31709364 0.26956571 0.62950404]
 [0.23699105 0.69854667 0.67491039]
 [0.34631505 0.90209034 0.42193918]] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
