## MEAN() IN NUMPY

NumPy's `mean()` function is a fundamental tool in array computation and analysis, used to calculate the arithmetic average of elements within an array.

*USAGE*:
The `mean()` function is typically used to compute the average of an entire array or along a specific axis, helping to summarize large datasets with a single representative number. It is especially useful in statistical analysis and data preprocessing.

*Mean = Average value*

Formula:
`Mean = Sum of values / Number of values`

*Real-World Use Cases of np.mean()*

✔ Business Analytics: 
- Average monthly sales.
- Average customer spending.
- Average rating in customer reviews
- Average daily website visitors

✔ Data Science & ML
- Normalizing/standardizing datasets(mean is used in feature scaling)
- Evaluating model errors (mean squared error uses mean)
- Average pixel intensity in image processing

✔ Finance
- Average stock price over a period
- Mean return of an investment
- Average revenue per quarter/year

In [1]:
import numpy as np

In [2]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],    # STUDENT BIRYANI
    [2, 120000, 140000, 160000, 190000],    # CHINESE RESTAURANT
    [3, 180000, 230000, 240000, 270000],    # PIZZA MAX
    [4, 200000, 210000, 240000, 270000],    # JARDIN CAFE
    [5, 165000, 176000, 380000, 295000]     # COCONUT GROVE CAFE
    ])

#average sales per restaurant.
avg_sale = np.mean(sales_data[:, 1:], axis=1)
print("Average Sale per Restaurant:",avg_sale)

Average Sale per Restaurant: [200000. 152500. 230000. 230000. 254000.]


#### NP.CUMSUM()
`Cumulative sales` are the running total of all sales over a specific period, calculated by adding each new sales figure to the total of all previous sales.

The `cumsum() function` is used to calculate the cumulative sum of array elements along a specified axis or across all axes.

*syntax*: `np.cumsum(array, axis=)`

Cumulative Sum → It keeps adding values one by one and returns the running total at each step.

In [4]:
cumsum_sale = np.cumsum(sales_data[:, 1:], axis=1)
print("Cumulative Sales: ",cumsum_sale)     

Cumulative Sales:  [[ 150000  330000  550000  800000]
 [ 120000  260000  420000  610000]
 [ 180000  410000  650000  920000]
 [ 200000  410000  650000  920000]
 [ 165000  341000  721000 1016000]]
