### ADVANCE OPERATION WITH BUSINESS EXAMPLE

**DATA STRUCTURE:**

[restaurant_id, 2022, 2023, 2024, 2025]

*sales_data* = np.array([

[1, 150000, 180000, 220000, 250000],   # STUDENT BIRYANI

[2, 120000, 140000, 160000, 190000],    # CHINESE RESTAURANT

[3, 180000, 210000, 240000, 270000],    # PIZZA MAX

[4, 200000, 230000, 240000, 270000],   # JARDIN CAFE

[5, 165000, 176000, 380000, 295000]  # COCONUT GROVE CAFE

])

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],    # STUDENT BIRYANI
    [2, 120000, 140000, 160000, 190000],    # CHINESE RESTAURANT
    [3, 180000, 230000, 240000, 270000],    # PIZZA MAX
    [4, 200000, 210000, 240000, 270000],    # JARDIN CAFE
    [5, 165000, 176000, 380000, 295000]     # COCONUT GROVE CAFE
    ])

print("-----SALES ANALYSIS-----")
print("\n Sales Data Shape", sales_data.shape)      #returns shape of sales data
print("\n Sample Data of 1st 3 Restaurants:\n", sales_data[:3])    #returns data from 0 indices till 3. We Used Slicing Method.

-----SALES ANALYSIS-----

 Sales Data Shape (5, 5)

 Sample Data of 1st 3 Restaurants:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 180000 230000 240000 270000]]


## NP.SUM() IN NUMPY
NumPy's `sum()` function is a powerful tool for array computation and analysis, allowing users to efficiently compute the sum of array elements along a specified axis. It is widely used for aggregating data in numerical computations.

The `sum()` function is used to calculate the total of array elements for numerical analysis or data manipulation. It can sum values along specified axes for multi-dimensional arrays to provide insights into datasets.

*SUM = Total of all values combined*

`Syntax: numpy.sum(a, axis=None, dtype=None, output)`

**Real-World Use Cases of np.sum()**
✔ Business & Sales
- Total yearly revenue
- Total units sold across regions
- Total marketing expenses

✔ Finance
- Total returns across multiple investments
- Total portfolio value
- Summing daily trading volumes

✔ AI & Machine Learning
- Calculating loss functions
- Summing gradients during backpropagation
- Total pixel intensity for image preprocessing

✔ Statistics & Data Analytics
- Computing weighted scores
- Summing survey responses
- Aggregating time-series data (e.g., total rainfall, total traffic)

✔ Scientific & Engineering
- Total energy consumption
- Summation of sensor readings
- Total distance traveled in tracking systems

## NP.MAX IN NUMPY
NumPy's `max()` function is a powerful tool for array computation and analysis, used to find the maximum value within an array or along a specified axis. It is essential for data analysis tasks where determining the largest value in a dataset is necessary.

NumPy's max() function is used to identify the largest value in an array or along a specified axis. It helps pinpoint peak values that represent upper bounds, extremes, or highest-performing metrics in data.
np.max() returns the maximum element from the entire array or maximum values across rows/columns when axis is specified.

*MAX = Highest value in a dataset*
`Syntax: numpy.max(array, axis=None, output)`

**Real-World Use Cases of np.max()**

✔ Business Analytics
- Highest monthly sales
- Maximum number of users in a day
- Peak demand/supply in inventory systems

✔ Finance
- Highest stock price during the year
- Maximum profit recorded in a quarter
- Peak trading volume

✔ AI & Machine Learning
- Highest accuracy among model results
- Peak activation in neural networks=
- Detecting outliers (extremely high values)

✔ IoT & Sensors
- Max temperature recorded by a sensor
- Peak CPU/GPU usage

## NP.MIN() IN NUMPY

The NumPy `min()` function is a part of Array Computation & Analysis tools, which is used to find the smallest value in an array. It is an efficient method for determining minimum values across various dimensions of a NumPy array.

NumPy's min() function returns the smallest value in an array or along a specific axis. It helps detect low-performance points, minimum readings, or worst-case values in datasets.
`np.min()`is used to compute the minimum numerical value across the entire dataset or per dimension.

*MIN = Lowest value in a dataset*


In [3]:
# Finding Total Sales/Year OR sales per year.

yearly_total = np.sum(sales_data[:, 1:],axis=1)
print("Total 4 Years Sales Data of each Restaurant: :",yearly_total)

#Row-wise Sales Total:
restaurant_sales_total_each = np.sum(sales_data[0,1:], axis=0) #will exclude restaurant id, sum total years of sale.
print(f"Student Biryani total sales:",restaurant_sales_total_each)

#Use axis= 0 for column wise operation(goes top to bottom). Use axis=1 for row wise operation(goes left to right).

# Min sales for each restaurant:
min_sales = np.min(sales_data[:, 1:], axis=1)
print("Minimum Sales/Restaurant:", min_sales)

# Max sales by each restaurants per year:
max_sales = np.max(sales_data[:, 1:], axis=0)
print("Maximum Sales Per Year:",max_sales)

# SIMPLE SUMMARY
# Operation 	 Meaning
# - axis=0	        Go down columns (per year)
# - axis=1	        Go across rows (per restaurant)
# - data[0, 1:]	    First row, ignore ID
# - data[:, 1:]	    All rows, ignore IDs


Total 4 Years Sales Data of each Restaurant: : [ 800000  610000  920000  920000 1016000]
Student Biryani total sales: 800000
Minimum Sales/Restaurant: [150000 120000 180000 200000 165000]
Maximum Sales Per Year: [200000 230000 380000 295000]


*PRACTICE IS CONTINUED IN MEAN_cumsum().IPYNB FILE*