### ADVANCE OPERATION WITH BUSINESS EXAMPLE

**DATA STRUCTURE:**

[restaurant_id, 2022, 2023, 2024, 2025]

*sales_data* = np.array([

[1, 150000, 180000, 220000, 250000],   # STUDENT BIRYANI

[2, 120000, 140000, 160000, 190000],    # CHINESE RESTAURANT

[3, 180000, 210000, 240000, 270000],    # PIZZA MAX

[4, 200000, 230000, 240000, 270000],   # JARDIN CAFE

[5, 165000, 176000, 380000, 295000]  # COCONUT GROVE CAFE

])

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],    # STUDENT BIRYANI
    [2, 120000, 140000, 160000, 190000],    # CHINESE RESTAURANT
    [3, 180000, 230000, 240000, 270000],    # PIZZA MAX
    [4, 200000, 210000, 240000, 270000],    # JARDIN CAFE
    [5, 165000, 176000, 380000, 295000]     # COCONUT GROVE CAFE
    ])

print("-----SALES ANALYSIS-----")
print("\n Sales Data Shape", sales_data.shape)      #returns shape of sales data
print("\n Sample Data of 1st 3 Restaurants:\n", sales_data[:3])    #returns data from 0 indices till 3. We Used Slicing Method.

-----SALES ANALYSIS-----

 Sales Data Shape (5, 5)

 Sample Data of 1st 3 Restaurants:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 180000 230000 240000 270000]]


In [3]:
# Finding Total Sales/Year OR sales per year.

yearly_total = np.sum(sales_data[:, 1:],axis=1)
print("Total 4 Years Sales Data of each Restaurant: :",yearly_total)

#Row-wise Sales Total:
restaurant_sales_total_each = np.sum(sales_data[0,1:], axis=0) #will exclude restaurant id, sum total years of sale.
print(f"Student Biryani total sales:",restaurant_sales_total_each)

#Use axis= 0 for column wise operation(goes top to bottom). Use axis=1 for row wise operation(goes left to right).

# Min sales for each restaurant:
min_sales = np.min(sales_data[:, 1:], axis=1)
print("Minimum Sales/Restaurant:", min_sales)

# Max sales by each restaurants per year:
max_sales = np.max(sales_data[:, 1:], axis=0)
print("Maximum Sales Per Year:",max_sales)

# SIMPLE SUMMARY
# Operation 	 Meaning
# - axis=0	        Go down columns (per year)
# - axis=1	        Go across rows (per restaurant)
# - data[0, 1:]	    First row, ignore ID
# - data[:, 1:]	    All rows, ignore IDs


Total 4 Years Sales Data of each Restaurant: : [ 800000  610000  920000  920000 1016000]
Student Biryani total sales: 800000
Minimum Sales/Restaurant: [150000 120000 180000 200000 165000]
Maximum Sales Per Year: [200000 230000 380000 295000]


*PRACTICE IS CONTINUED IN MEAN().IPYNB FILE*