## Practice with real world data

### ADVANCE OPERATION WITH BUSINESS EXAMPLE

**DATA STRUCTURE: [restaurant_id, 2022, 2023, 2024, 2025]**

In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],    # STUDENT BIRYANI
    [2, 120000, 140000, 160000, 190000],    # CHINESE RESTAURANT
    [3, 180000, 210000, 240000, 270000],    # PIZZA MAX
    [4, 200000, 230000, 240000, 270000],    # JARDIN CAFE
    [5, 165000, 176000, 380000, 295000]     # COCONUT GROVE CAFE
    ])

print("-----SALES ANALYSIS-----")
print("\n Sales Data Shape", sales_data.shape)      #returns shape of sales data
print("\n Sample Data of 1st 3 Restaurants:\n", sales_data[:3])       #returns data from 0 indices till 3. We Used Slicing Method.

-----SALES ANALYSIS-----

 Sales Data Shape (5, 5)
Sample Data of 1st 3 Restaurants:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 180000 210000 240000 270000]]
