# SCALAR, VECTOR, MATRIX, TENSOR.

In [14]:
import numpy as np

### SCALAR:

A scalar is a single number — just one value, no direction, no dimensions.

In [15]:
scalar = np.array(7)

print(scalar)
print("Dimensions:", scalar.ndim)

7
Dimensions: 0


### VECTOR:
A vector is simply a list of numbers — one direction, one dimension.

A vector has magnitude (size) and direction.

Vectors are 1D arrays.

Used to represent things like coordinates (x, y, z), features, or inputs in ML.

In [16]:
vector = np.array([1,2,3])
print(f"Vector:{vector}")
print(f"Dimension:{vector.ndim}")
print(f"Matrix Shape:{vector.shape}")



Vector:[1 2 3]
Dimension:1
Matrix Shape:(3,)


### Matrix:
In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.

Rows run horizontally and columns run vertically.

A matrix has rows and columns, like an Excel sheet or a table.

R X C = rows x columns.

rows == columns → square matrix


In [17]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(f"Matrix:\n{matrix}")
print(f"Dimension:{matrix.ndim}")
print(f"Matrix Shape:{matrix.shape}")


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension:2
Matrix Shape:(3, 3)


### Tensor:

Tensor is often used to refer to a multidimensional array.

When you stack multiple matrices together — you get a 3D array or Tensor.

Shape (2, 2, 3) means: 2 matrices, each matrix has 2 rows and 3 columns

In [18]:
tensor = np.array([
                    [[1,2,3],
                    [4,5,6]],
                   
                    [[7,8,9],
                    [10,11,12]]
                    ])

print(f"Tensor:\n{tensor}")
print(f"Dimension:{tensor.ndim}")
print(f"Matrix Shape:{tensor.shape}")

Tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension:3
Matrix Shape:(2, 2, 3)


✅ Practice Tasks

Create a scalar, vector, matrix, and 3D tensor in one script.

Print their values, shape, and number of dimensions using .shape and .ndim.

Observe how NumPy treats each one differently.

In [19]:
#TASK
scalar_array = np.array(1)
print(scalar_array)

vector_array = np.array([1,2,3,4,5])
print(vector_array)

matrix_array = np.array([['1one','1two','1three'],
                         ['2one','2two','2three'],
                         ['3one','3two','3three']])
print(matrix_array)
print("Shape",matrix_array.shape)
print("Dimension:", matrix_array.ndim)

tensor_array = np.array([
                         [[1,2,3],
                         [4,5,6]],
                         [[7,8,9],
                         [10,11,12]]
                        ])
print(tensor_array)
print("Shape",tensor_array.shape)
print("Dimension",tensor_array.ndim)


1
[1 2 3 4 5]
[['1one' '1two' '1three']
 ['2one' '2two' '2three']
 ['3one' '3two' '3three']]
Shape (3, 3)
Dimension: 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape (2, 2, 3)
Dimension 3
