# VECTOR, MATRIX, TENSOR.

In [1]:
import numpy as np

### SCALAR:

A scalar is a single number — just one value, no direction, no dimensions.

In [14]:
scalar = np.array(7)

print(scalar)
print("Dimensions:", scalar.ndim)

7
Dimensions: 0


### VECTOR:
A vector is simply a list of numbers — one direction, one dimension.

A vector has magnitude (size) and direction.

In [7]:
vector = np.array([1,2,3])
print(f"Vector:{vector}")
print(f"Dimension:{vector.ndim}")
print(f"Matrix Shape:{vector.shape}")



Vector:[1 2 3]
Dimension:1
Matrix Shape:(3,)


### Matrix:
In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.

Rows run horizontally and columns run vertically.

A matrix has rows and columns, like an Excel sheet or a table.

R X C = rows x columns.

rows == columns → square matrix


In [6]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(f"Matrix:\n{matrix}")
print(f"Dimension:{matrix.ndim}")
print(f"Matrix Shape:{matrix.shape}")


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension:2
Matrix Shape:(3, 3)


### Tensor:

Tensor is often used to refer to a multidimensional array.

When you stack multiple matrices together — you get a 3D array or Tensor.

In [13]:
tensor = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12]]])

print(f"Tensor:\n{tensor}")
print(f"Dimension:{tensor.ndim}")
print(f"Matrix Shape:{tensor.shape}")

Tensor:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
Dimension:3
Matrix Shape:(1, 4, 3)
