# VECTOR, MATRIX, TENSOR.

In [1]:
import numpy as np

### VECTOR:
A vector is simply a list of numbers — one direction, one dimension.

A vector has magnitude (size) and direction.

In [2]:
vector = np.array([1,2,3])
print(f"Vector:{vector}")

Vector:[1 2 3]


### Matrix:
In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.

Rows run horizontally and columns run vertically.

A matrix has rows and columns, like an Excel sheet or a table.

R X C = rows x columns.

rows == columns → square matrix


In [8]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(f"Matrix:\n{matrix}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
